# Disable Ubuntu's Bash completion crap
#. ~/proj/etc/profile/bashrc

# Generic shell ENV initialisation, named after Bash because of its special
# behaviour. Typically this can be appended to the skeleton ~/.bashrc file.

set -o nounset

alias ls='ls --color=auto'
alias patch='patch --binary'

HISTSIZE=2000
HISTFILESIZE="$HISTSIZE"
HISTCONTROL=erasedups

# Manually remove duplicates in saved history because Bash only removes them
# from memory for each new entry added, and saved entries are not removed
# when appending the history file
if test -e ~/.bash_history; then
    NEW=~/".bash_history~$$"
    if ! {
        awk '
            {line[NR] = $0; last[$0] = NR}
            END {for(i = 1; i <= NR; ++i)
                if(last[line[i]] == i) print line[i]}
        ' ~/.bash_history > "$NEW" &&
        mv "$NEW" ~/.bash_history
    }; then
        rm "$NEW"
    fi
fi

CSI="'\e['" TEXT='"(exit $?)"'; trap "printf $CSI'1;41;37m'$TEXT$CSI'0m\n'" ERR
trap exit TERM  # Apparently ignored by default so that "kill 0" applies to process group except shell
